import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Slide, ToastContainer } from "react-toastify";
import ScrollToTopButton from "@/components/ScrollToTopButton";
import { AuthProvider } from "@/contexts/AuthContext";
// import ThemeSwitch from "@/components/ThemeSwitch";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartHealth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Providers>
          <AuthProvider>
            <Header />
            <main className="flex-1 bg-blue-50">
              {children}
            </main>
            <ScrollToTopButton />
            <Footer />
            <ToastContainer
              position="top-right"
              autoClose={2000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              // theme="dark"
              transition={Slide}
            />
            {/* <ThemeSwitch /> */}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
